### PR TITLE
version 1.2.0

### PR DESCRIPTION
**Pull request by zvin**
updated:
 * package.json
 * CHANGELOG
 * README

### CODE REVIEW

**Comment by lurch** [comment]
I'll approve after you add partition.type to the README ;-)

**Comment by zvin** [comment]
@lurch added

**Comment by lurch** [comment]
Ah, looks like `README.md` is supposed to be autogenerated from `README.hbs` - @jviotti can probably provide guidance here...

**Comment by jviotti** [comment]
Yeah, you need to edit `docs/README.hbs` and run `npm run readme`

**Review by jviotti — APPROVED** [review]

**Comment by zvin** [comment]
thanks @jviotti

**Pull request merged**
